language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --prefer-dist --no-interaction

script: php bin/phing build.ci

after_script:
  - php bin/coveralls -v
